language: java
jdk:
  - oraclejdk7
script: mvn clean install
branches:
  only:
  - master
notifications:
  email:
  - renaud.richardet@gmail.ch
before_script:
 - "echo $JAVA_OPTS"
 - "export JAVA_OPTS=-Xmx1G"
